# Generated by Django 3.2 on 2021-04-21 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id_bodega', models.IntegerField(primary_key=True, serialize=False)),
                ('cant_producto', models.IntegerField()),
                ('nom_producto', models.CharField(max_length=50)),
                ('fecha_recepcionada', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
            ],
            options={
                'db_table': 'bodega',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut_empresa', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nom_empresa', models.CharField(max_length=20)),
                ('tel_empresa', models.CharField(max_length=15)),
                ('direc_empresa', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_departamento', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'departamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('cod_factura', models.AutoField(primary_key=True, serialize=False)),
                ('detalle_factura', models.CharField(max_length=50)),
                ('fecha_factura', models.DateField()),
                ('valor_factura', models.IntegerField()),
                ('valor_iva', models.FloatField()),
                ('cliente_hostal_clarita_rut_hostal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cliente_clarita', to='core.cliente')),
                ('cliente_rut_empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
            ],
            options={
                'db_table': 'factura',
                'managed': True,
                'unique_together': {('cod_factura', 'cliente_rut_empresa', 'cliente_hostal_clarita_rut_hostal')},
            },
        ),
        migrations.CreateModel(
            name='HostalClarita',
            fields=[
                ('rut_hostal', models.IntegerField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=50)),
                ('tel_hostal', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'hostal_clarita',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('rut_huesped', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nom_huesped', models.CharField(max_length=15)),
                ('apellido_huesped', models.CharField(max_length=15)),
                ('tel_huesped', models.CharField(max_length=12)),
                ('correo_huesped', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'huesped',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Minuta',
            fields=[
                ('id_minuta', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_minuta', models.CharField(max_length=20)),
                ('valor_minuta', models.BigIntegerField()),
            ],
            options={
                'db_table': 'minuta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_emision_pedido', models.DateField()),
                ('fecha_recepcion', models.DateField()),
                ('estado_pedido', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'pedido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nom_producto', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('valor', models.BigIntegerField()),
                ('bodega_id_bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bodega')),
                ('pedido_id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pedido')),
            ],
            options={
                'db_table': 'producto',
                'managed': True,
                'unique_together': {('id_producto', 'pedido_id_pedido', 'bodega_id_bodega')},
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nom_usuario', models.CharField(max_length=20)),
                ('clave', models.CharField(max_length=12)),
                ('tipo_usuario', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id_tipo_habitacion', models.IntegerField(primary_key=True, serialize=False)),
                ('datelle_habitacion', models.CharField(max_length=50)),
                ('valor_habitacion', models.IntegerField()),
                ('tipo_cama', models.CharField(max_length=50)),
                ('hostal_clarita_rut_hostal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hostalclarita')),
            ],
            options={
                'db_table': 'tipo_habitacion',
                'managed': True,
                'unique_together': {('id_tipo_habitacion', 'hostal_clarita_rut_hostal')},
            },
        ),
        migrations.CreateModel(
            name='Cocina',
            fields=[
                ('id_cocina', models.IntegerField(primary_key=True, serialize=False)),
                ('departamento_id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.departamento')),
            ],
            options={
                'db_table': 'cocina',
                'managed': True,
                'unique_together': {('id_cocina', 'departamento_id_departamento')},
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='hostal_clarita_rut_hostal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hostalclarita'),
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rut_proveedor', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nom_proveedor', models.CharField(max_length=20)),
                ('rubro_proveedor', models.CharField(max_length=20)),
                ('tel_proveedor', models.CharField(max_length=12)),
                ('producto_bodega_id_bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producto_idbodega', to='core.producto')),
                ('producto_id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producto_idproducto', to='core.producto')),
                ('producto_pedido_id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
            ],
            options={
                'db_table': 'proveedor',
                'managed': True,
                'unique_together': {('rut_proveedor', 'producto_id_producto', 'producto_pedido_id_pedido', 'producto_bodega_id_bodega')},
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion_compra', models.CharField(max_length=50)),
                ('valor_compra', models.IntegerField()),
                ('factura_cliente_hostal_clarita_rut_hostal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factura_hostal', to='core.factura')),
                ('factura_cliente_rut_empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factura_empresa', to='core.factura')),
                ('factura_cod_factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.factura')),
                ('huesped_rut_huesped', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.huesped')),
            ],
            options={
                'db_table': 'orden_compra',
                'managed': True,
                'unique_together': {('id_orden', 'huesped_rut_huesped', 'factura_cod_factura', 'factura_cliente_rut_empresa', 'factura_cliente_hostal_clarita_rut_hostal')},
            },
        ),
        migrations.CreateModel(
            name='EstadoHabitacion',
            fields=[
                ('id_habitacion', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_estado', models.CharField(max_length=20)),
                ('tipo_habitacion_hostal_clarita_rut_hostal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habitacion_hostal', to='core.tipohabitacion')),
                ('tipo_habitacion_id_tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_habitacion', to='core.tipohabitacion')),
            ],
            options={
                'db_table': 'estado_habitacion',
                'managed': True,
                'unique_together': {('id_habitacion', 'tipo_habitacion_id_tipo_habitacion', 'tipo_habitacion_hostal_clarita_rut_hostal')},
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut_empleado', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('departamento_id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.departamento')),
                ('hostal_clarita_rut_hostal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hostalclarita')),
                ('pedido_id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pedido')),
            ],
            options={
                'db_table': 'empleado',
                'managed': True,
                'unique_together': {('rut_empleado', 'hostal_clarita_rut_hostal', 'departamento_id_departamento', 'pedido_id_pedido')},
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id_comanda', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_comanda', models.CharField(max_length=50)),
                ('cocina_departamento_id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cocina_depa', to='core.cocina')),
                ('cocina_id_cocina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cocina')),
                ('huesped_rut_huesped', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.huesped')),
                ('minuta_id_minuta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.minuta')),
            ],
            options={
                'db_table': 'comanda',
                'managed': True,
                'unique_together': {('id_comanda', 'cocina_id_cocina', 'cocina_departamento_id_departamento', 'minuta_id_minuta', 'huesped_rut_huesped')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('rut_empresa', 'hostal_clarita_rut_hostal')},
        ),
    ]
