# Generated by Django 3.2 on 2021-04-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tipo_usuario',
                'managed': True,
            },
        ),
    ]
