# Generated by Django 3.2 on 2021-05-05 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tipousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nombre_producto',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
