# Generated by Django 3.2 on 2021-05-27 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pedido_nombre_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipohabitacion',
            old_name='tipo_cama',
            new_name='tipo_hab',
        ),
    ]
