# Generated by Django 3.2 on 2021-05-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210526_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nom_proveedor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rubro_proveedor',
            field=models.CharField(max_length=50),
        ),
    ]
