# Generated by Django 3.2 on 2021-05-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210527_2235'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proveedor',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='producto_bodega_id_bodega',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='producto_pedido_id_pedido',
        ),
    ]
