# Generated by Django 3.2 on 2021-05-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210528_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='producto_id_producto',
        ),
    ]
