# Generated by Django 3.1.2 on 2021-05-31 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_registrohabitacion'),
        ('core', '0009_reserva'),
    ]

    operations = [
    ]
