# Generated by Django 3.2 on 2021-06-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20210531_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='comedor',
            fields=[
                ('id_plato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plato', models.CharField(max_length=50)),
                ('detalle', models.CharField(max_length=100)),
                ('valor_plato', models.IntegerField()),
                ('tipo_servicio', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'comedor',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='registroHabitacion',
        ),
    ]
