# Generated by Django 3.2 on 2021-07-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210601_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura_hostal',
            fields=[
                ('cod_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_factura', models.DateField()),
                ('rut_empresa', models.CharField(max_length=100)),
                ('detalle_factura', models.CharField(max_length=800)),
                ('valor_factura', models.IntegerField()),
                ('valor_iva', models.IntegerField()),
            ],
            options={
                'db_table': 'factura_hostal',
                'managed': True,
            },
        ),
    ]
