# Generated by Django 3.2 on 2021-07-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_factura_hostal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepcion_pedido',
            fields=[
                ('cod_proveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('categoria_producto', models.IntegerField()),
                ('fecha_vencimiento', models.IntegerField()),
                ('numero_secuencial', models.IntegerField()),
                ('sku', models.IntegerField()),
            ],
            options={
                'db_table': 'recepcion_pedido',
                'managed': True,
            },
        ),
    ]
