# Generated by Django 3.2 on 2021-07-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_recepcion_pedido_nom_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepcion_Pedidoh',
            fields=[
                ('cod_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cod_proveedor', models.IntegerField()),
                ('nom_producto', models.CharField(max_length=100)),
                ('categoria_producto', models.IntegerField()),
                ('fecha_vencimiento', models.IntegerField()),
                ('numero_secuencial', models.IntegerField()),
                ('sku', models.BigIntegerField()),
            ],
            options={
                'db_table': 'recepcion_pedidoh',
                'managed': True,
            },
        ),
    ]
